"""Isolated NeuroSim source preparation and compilation."""

from __future__ import annotations

import hashlib
import json
import platform
import shutil
import subprocess
from pathlib import Path
from shutil import which
from dataclasses import dataclass

from .config import HardwareConfig
from .source import SourceIdentity, source_build_root, validate_neurosim_source


class BuildError(RuntimeError):
    """Raised when an isolated backend build fails."""


@dataclass(frozen=True)
class BuildArtifact:
    source_copy: Path
    build_directory: Path
    manifest_path: Path
    executable: Path | None
    cache_key: str
    source_identity: SourceIdentity
    build_root: Path


def _config_hash(config: HardwareConfig) -> str:
    encoded = json.dumps(
        {key: value for key, value in config.to_dict().items() if key != "config_path"},
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _generated_config(config: HardwareConfig) -> str:
    p = config.precision
    a = config.array
    m = config.memory
    return (
        "// Generated by kws.hardware.neurosim; reference assumptions only.\n"
        f"#define KWS_NEUROSIM_WEIGHT_BITS {p.weight_bits}\n"
        f"#define KWS_NEUROSIM_ACTIVATION_BITS {p.activation_bits}\n"
        f"#define KWS_NEUROSIM_CELL_BITS {p.cell_bits}\n"
        f"#define KWS_NEUROSIM_ADC_BITS {p.adc_bits}\n"
        f"#define KWS_NEUROSIM_ARRAY_ROWS {a.rows}\n"
        f"#define KWS_NEUROSIM_ARRAY_COLS {a.cols}\n"
        f"#define KWS_NEUROSIM_COLUMNS_PER_ADC {a.columns_per_adc}\n"
        f"#define KWS_NEUROSIM_RON_OHM {m.resistance_on_ohm:.17g}\n"
        f"#define KWS_NEUROSIM_ROFF_OHM {m.resistance_off_ohm:.17g}\n"
    )


def _patch_official_v21_source(source_copy: Path, config: HardwareConfig) -> None:
    """Patch only the isolated official V2.1 copy with requested hardware options."""

    root = source_copy / "Training_pytorch" / "NeuroSIM"
    param_path = root / "Param.cpp"
    if not param_path.is_file():
        return
    text = param_path.read_text(encoding="utf-8")
    replacements = {
        "memcelltype = 3;": "memcelltype = 2;",
        "trainingEstimation = true;": "trainingEstimation = false;",
        "cellBit = 5;": f"cellBit = {config.precision.cell_bits};",
        "levelOutput = 64;": f"levelOutput = {2 ** config.precision.adc_bits};",
        "technode = 32;": f"technode = {config.technology.node_nm};",
        "temp = 300;": f"temp = {config.technology.temperature_k:g};",
        "clkFreq = 1e9;": f"clkFreq = {config.technology.clock_hz:.17g};",
        "numRowSubArray = 128;": f"numRowSubArray = {config.array.rows};",
        "numColSubArray = 128;": f"numColSubArray = {config.array.cols};",
        "numColMuxed = 8;": f"numColMuxed = {config.array.columns_per_adc};",
        "resistanceOn = 240e3;": f"resistanceOn = {config.memory.resistance_on_ohm:.17g};",
        "resistanceOff = 240e3*100;": f"resistanceOff = {config.memory.resistance_off_ohm:.17g};",
        "writeVoltage = 4;": f"writeVoltage = {config.memory.write_voltage_v:g};",
        "writePulseWidth = 50e-9;": f"writePulseWidth = {config.memory.write_pulse_width_s:.17g};",
        "readVoltage = 0.5;": f"readVoltage = {config.memory.read_voltage_v:g};",
        "readPulseWidth = 10e-9;": f"readPulseWidth = {config.memory.read_pulse_width_s:.17g};",
        "resistanceAccess = 15e3;": f"resistanceAccess = {config.memory.access_resistance_ohm:.17g};",
        "novelMapping = true;": f"novelMapping = {'true' if config.simulation.mapping == 'novel' else 'false'};",
        "pipeline = false;": f"pipeline = {'true' if config.simulation.pipeline else 'false'};",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    param_path.write_text(text, encoding="utf-8")


def prepare_isolated_build(
    source_root: str | Path,
    config: HardwareConfig,
    cache_dir: str | Path,
    *,
    patch_version: str = "v1",
) -> BuildArtifact:
    identity = validate_neurosim_source(source_root)
    key_material = f"{identity.source_sha256}:{_config_hash(config)}:{patch_version}".encode()
    cache_key = hashlib.sha256(key_material).hexdigest()
    root = Path(cache_dir).expanduser().resolve() / "v21" / cache_key
    source_copy = root / "source"
    build_directory = root / "build"
    manifest_path = root / "build_manifest.json"
    root.mkdir(parents=True, exist_ok=True)
    if not source_copy.exists():
        shutil.copytree(
            identity.root,
            source_copy,
            ignore=shutil.ignore_patterns(".git", "build", "__pycache__"),
        )
    _patch_official_v21_source(source_copy, config)
    build_root = source_build_root(source_copy)
    source_copy.joinpath("GeneratedUserConfig.inc").write_text(
        _generated_config(config), encoding="utf-8"
    )
    build_directory.mkdir(parents=True, exist_ok=True)
    manifest = {
        "schema_version": 1,
        "backend": config.backend,
        "cache_key": cache_key,
        "patch_version": patch_version,
        "source": {
            "root": str(identity.root),
            "sha256": identity.source_sha256,
            "git_remote": identity.git_remote,
            "git_branch": identity.git_branch,
            "git_commit": identity.git_commit,
            "dirty": identity.dirty,
        },
        "hardware_config": {
            key: value for key, value in config.to_dict().items() if key != "config_path"
        },
        "warnings": list(identity.warnings),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return BuildArtifact(
        source_copy=source_copy,
        build_directory=build_directory,
        manifest_path=manifest_path,
        executable=None,
        cache_key=cache_key,
        source_identity=identity,
        build_root=build_root,
    )


def compile_neurosim(
    artifact: BuildArtifact,
    *,
    make_target: str | None = None,
    timeout_seconds: float = 300,
) -> BuildArtifact:
    command = ["make"]
    if platform.system() == "Darwin" and Path("/opt/homebrew/opt/llvm/bin/clang++").is_file():
        command.extend(
            [
                "CXX=/opt/homebrew/opt/llvm/bin/clang++",
                "CXXFLAGS=-fPIC -g -O3 -std=c++0x -Wno-parentheses",
            ]
        )
    if make_target:
        command.append(make_target)
    stdout = ""
    stderr = ""
    return_code = -1
    try:
        result = subprocess.run(
            command,
            cwd=artifact.build_root,
            capture_output=True,
            text=True,
            check=False,
            timeout=timeout_seconds,
        )
        stdout = result.stdout
        stderr = result.stderr
        return_code = result.returncode
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        stderr += "\nprocess timed out\n"
    except OSError as exc:
        stderr = str(exc)
    (artifact.build_directory / "compile.stdout.txt").write_text(stdout, encoding="utf-8")
    (artifact.build_directory / "compile.stderr.txt").write_text(stderr, encoding="utf-8")
    if return_code != 0:
        raise BuildError(
            f"NeuroSim compilation failed with return code {return_code}; "
            f"see {artifact.build_directory}"
        )
    manifest = json.loads(artifact.manifest_path.read_text(encoding="utf-8"))
    manifest["compile"] = {
        "command": command,
        "return_code": return_code,
        "stdout": str(artifact.build_directory / "compile.stdout.txt"),
        "stderr": str(artifact.build_directory / "compile.stderr.txt"),
    }
    artifact.manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    executable = artifact.build_root / "main"
    manifest["executable"] = str(executable) if executable.is_file() else None
    artifact.manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return BuildArtifact(
        source_copy=artifact.source_copy,
        build_directory=artifact.build_directory,
        manifest_path=artifact.manifest_path,
        executable=executable if executable.is_file() else None,
        cache_key=artifact.cache_key,
        source_identity=artifact.source_identity,
        build_root=artifact.build_root,
    )
